anduril/jetpack-nixos

modules/default.nix
By default libEGL_nvidia.so.0 tries to find EGL configurations in either /usr/share/egl/egl_external_platform.d or /etc/egl/egl_external_platform.d but in NixOS it is stored in /run/opengl-driver/share/egl/egl_external_platform.d. In order to fix it we can set an undocumented variable __EGL_EXTERNAL_PLATFORM_CONFIG_DIRS to the correct path. With this change it is possible to run Weston with nvidia-drm driver on Nvidia Jetson AGX Orin.
=> Fix Nvidia Wayland EGL

cuda-packages.nix
Add a symlink from `libcuda.so` to `libcuda.so.1` in order to appease certain libraries that explicitly look for `libcuda.so.1`.
=> Symlink libcuda.so.1

flake.nix
Remove outdated comment related to failing kernel build. This issue was already fixed in Pull Request #7.
Signed-off-by: Mika Tammi <mika.tammi@unikie.com>
The outdated comment causes confusion
This change doesn't actually cause any functional changes, merely removes a comment from the flake.nix.
As a test, succesfully did `nix build .#packages.aarch64-linux.iso_minimal` against the latest nixpkgs master. There are no kernel build errors.
=> Remove outdated kernel build fail comment

flake.lock, flake.nix
Bumped nixpkgs to NixOS 22.11
Tested an Orin AGX system can switch from 22.05 to 22.11. Need to test flashing and installer ISO.
=> Bump nixpkgs to nixos-22.11

default.nix, kernel/default.nix, modules/default.nix
NVIDIA seems to have some level of support for running a kernel with the PREEMPT_RT patchset. They include the patches under `rt-patches/` and have instructions to enable the realtime kernel here:
https://docs.nvidia.com/jetson/archives/r35.1/DeveloperGuide/text/SD/Kernel/KernelCustomization.html#to-build-the-real-time-kernel
This adds a `hardware.nvidia-jetpack.kernel.realtime` option which, if set to true, enables the PREEMPT_RT patches and kernel options.
Only tested this builds. Will test on device soon.
=> Add realtime.kernel option to enable PREEMPT_RT patches

cuda-packages.nix, cuda-samples.patch, samples.nix
The NVRTC (Runtime Compiler) in `libnvrtc.so` wasn't correctly loading `libnvrtc-builtins.so` at runtime, since its own lib directory was missing from the RPATH.  Additionally, this PR fixes building the `*_nvrtc` examples from cuda-samples.
Tested by running the following on a Xavier AGX:
```
$ nix build .#samples.cuda-samples
$ cd ./result/data
$ ../bin/clock_nvrtc
CUDA Clock sample
> Using CUDA Device [0]: Xavier
> Using CUDA Device [0]: Xavier
> GPU Device has SM 7.2 compute capability
Average clocks/block = 3272.921875
```
=> Fix NVRTC and build NVRTC samples

README.md
Following the original instructions didn't work, so I fixed them.
I was able to flash my Jetson using these new instructions.
=> doc: fix the instructions for flashing firmware

kernel/default.nix
This ensures that systems with IPv6 configured can successfully start their `firewall.service`s (at least on master nixpkgs).
I built a system with `networking.enableIPv6` and checked `systemctl status firewall` which is now successful.
=> Enable IPv6 NF_MATCH kernel parameters

cuda-packages.nix
In cross-compile scenarios, the directory containing `libgcc_s.so` and other such
libraries is actually under a target-specific directory such as
`${stdenv.cc.cc.lib}/aarch64-unknown-linux-gnu/lib/` rather than just plain `/lib` which
makes `autoPatchelfHook` fail at finding them libraries.
I cross-built a system that contains `tensorrt` in its `systemPackages`, deployed it, verified that `trtexec` manages to print out its usage when invoked without arguments.
=> cudaPackages: fix discovery of gcc libraries for cross builds

default.nix, edk2-uefi-dtb.patch, modules/flash-script.nix
The Jetpack 5.1 update inadvertantly broke this patch--which was inadvertantly not being applied to the configurations I was testing on.  Additionally, this PR just applies this fix unconditionally.
Tested flashing on Xavier AGX, Xavier NX, and Orin AGX
=> Fix UEFI dtb patch, apply for all devices.

README.md, modules/default.nix, modules/devices.nix
This PR adds support for the Orin NX, running on the Xavier NX devkit.
There are two known issues:
1) Flashing a factory Orin NX works the first time, but fails the second time: https://github.com/anduril/jetpack-nixos/issues/33
2) It currently requires the USB_OTG kernel config option to be disabled, or else the kernel crashes at boot: https://github.com/anduril/jetpack-nixos/issues/34
Flashed and booted NixOS on an Orin NX
=> Support for Orin NX

kernel/display-driver.nix
Why: nvidia-display-driver package broke
* NVIDIA changed their tag to point to a different commit hash, resulting in hash mismatch. Use commit hash instead of the tag to point to a revision
* Fix directory name where the source package gets unpacked
Tested using AGX Orin Devkit. I was able to launch Weston, and graphics were usable in kmsdrm mode. I didn't test the legacy mode which supports X11.
=> Fix nvidia-display-driver

default.nix, jetson-benchmarks/0001-disable-disruptive-system_check.patch, jetson-benchmarks/default.nix, jetson-benchmarks/scripts/run-all-jetson-benchmarks, jetson-benchmarks/scripts/run-jetson-benchmarks, jetson-benchmarks/scripts/run-resnet-jetson-benchmarks
Added support for building the jetson benchmark result from nvidia at: https://github.com/NVIDIA-AI-IOT/jetson_benchmarks/, these benchmarks are valuable since Nvidia publishes expected results that allow users to compare whether their platform is performing as expected
Tested on Orin NX. The benchmark is built differently based on whether it runs on NX, Orin AGX, Xavier, AGX, etc. Right now only the one for NX is predefined but others can be defined as well
=> Added initial jetson benchmarks

samples.nix
Disables the VPI2 test for now due to the failure here: https://github.com/anduril/jetpack-nixos/issues/44
This lets us continue automated testing for the tests that actually do work.
=> Disable VPI2 test for now

default.nix, tegra-eeprom-tool.nix
Adds [tegra-eeprom-tool](https://github.com/oe4t/tegra-eeprom-tool), which is useful for reading and writing from the EEPROM on jetson devices: https://docs.nvidia.com/jetson/archives/r34.1/DeveloperGuide/text/HR/JetsonEepromLayout.html
Builds and runs successfully on a Xavier AGX.
=> Add tegra-eeprom-tool

modules/default.nix
Add /etc/nv_tegra_release file from l4t-core deb.  Upstream L4T linux has this file, and it makes it easier for a user to tell what version of L4T their NixOS system was built from.
Ensured a Xavier AGX image builds
=> Add /etc/nv_tegra_release file from l4t-core deb

default.nix, jetson-firmware.nix
Simplify the version a bit to just be `l4tVersion`. This version is accessible from Linux via /sys/class/dmi/id/bios_version
None
=> Set UEFI version to be the l4tVersion

kernel/default.nix
This removes the hacked system from kernel/default.nix. The original purpose of the hacked system is to override the kernel config to make USB_XHCI_TEGRA builtin. Right now kernel configs specified using `structuredExtraConfig` will not override what is specified in the platform but configs specified using `extraConfig` of kernel patches will(this is an issue with the current nix code, we might want to make an issue upstream to document or fix it)
The newly built kernels boot on an Orin NX
=> Removed Hacked System from Kernel Build Process

default.nix, kernel/default.nix
[This PR](https://github.com/anduril/jetpack-nixos/pull/55) inadvertently broke the `boot.kernelPatches` NixOS option, and those settings were not being applied.
---
This PR uses buildLinux arguments like is done in upstream nixpkgs, where append or merge our kernel's default.nix extra (structured) config with what is passed va callPackage
See `pkgs/os-specific/linux/kernel` in nixpkgs for examples.
Tested by building `config.boot.kernelPackages.kernel.configfile` on a NixOS machine that sets `boot.kernelPatches` and noted that it was working before, is broken currently on master, and is working again after merging this PR.
=> Fix config.boot.kernelPatches not being applied

README.md, bup-bl-only.patch, default.nix, device-pkgs.nix, flake.nix, flash-from-device.nix, flash-from-device.sh, flash-script.nix, flash-tools.nix, flash.sh.patch, jetson-firmware.nix, modules/default.nix, modules/flash-script.nix
As an alternative to the traditional flashing scripts, we now have the
option to RCM boot into a minimal Linux system that can write out the
firmware itself.  This is done by upstream in
`tools/kernel_flash/initrd_flash` in the BSP package.  Flashing in this
manner also resolved the issue (https://github.com/anduril/jetpack-nixos/issues/33) where we were unable to flash an
Orin NX after it had been initially flashed from the factory.
Initrd-based flashing will likely be necessary if we ever want to have
the flashing script write out a full NixOS system to an NVMe drive.
Unlike the initrd flashing scripts from NVIDIA's BSP, or from OE4T
meta-tegra, our script is explicitly "multi-spec" and includes firmware
for all Jetson variants associated with a given soc/carrierboard combo.
This means …
=> Add initrd-based flashing scripts 

kernel/add-mno-outline-atomics-for-aarch64.patch, kernel/display-driver.nix
Recent versions of nixos-unstable have moved from GCC 9 to 12, which breaks to build. Flag -mno-outline-atomics is needed for the kernel module, to avoid errors sucs as:
ERROR: modpost: "__aarch64_cas4_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_ldadd8_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_ldadd4_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_cas8_sync" [/nvidia.ko] undefined!
This change has been backported from jetson_35.3.1
**What has changed as a result of this PR? Why was the change made?**
display-driver did not build with nixos-unstable channel. A small change adding one flag to kernel module build was backported from 35.3.1 to 35.2.1 to make it builable with recent nixos-unstable versions.
Tested that it builds with latest nixos-unstable, …
=> Fix display-driver build on GCC 12

LICENSE, README.md, default.nix, device-pkgs.nix, flake.nix, flash-from-device.nix, flash-from-device.sh, flash-script.nix, flash-tools.nix, modules/default.nix, modules/devices.nix, modules/flash-script.nix, ota-utils/default.nix, ota-utils/ota-apply-capsule-update.sh, ota-utils/ota-check-firmware.sh, ota-utils/ota-setup-efivars.sh, ota-utils/ota_helpers.func, uefi-firmware.nix
To determine if the currently running firmware matches the software, run, `ota-check-firmware`:
```
$ ota-check-firmware
Current firmware version is: 35.2.1
Current software version is: 35.2.1
```
If these versions do not match, you can update your firmware using the UEFI Capsule update mechanism. The procedure to do so is below:
To build a capsule update file, build the
`config.system.build.devicePkgs.uefiCapsuleUpdate` attribute from your NixOS build. For the standard devkit configurations supported in this repository, one could also run (for example),
`nix build .#uefi-capsule-update-xavier-nx-emmc-devkit`. Unfortunately, due to some limitations from nvidia's scripts, this build needs to happen on an `x86_64-linux` machine. This will produce a file that you can scp (no need for `nix …
=> Add UEFI capsule update scripts

modules/flash-script.nix
On some BSPs, the config filename does not match the target_board string that should ultimately make it into the boardspec string. So, we'll add a new option that defaults to targetBoard which can be overridden on for those BSPs.
Tested on a vendor's carrier board that requires this.
=> Add configFileName option. Default to targetBoard

modules/flash-script.nix
Add patch to fix the way edk2 handles TnSpec strings, which need to be zero-terminated
Just building edk2
=> Add fix to EDK2 TnSpec handling

device-pkgs.nix, flash-script.nix
Use `writeShellApplications` instead of `writeShellScriptBin` to get shellcheck automatically and also to make it work nicely with `nix run`
Nix build works fine and flash script for an Orin NX runs without errors.
=> Use write shell applications for flashing scripts

0001-nvoptee-no-install-makefile.patch, default.nix, device-pkgs.nix, flash-script.nix, modules/default.nix, optee.nix
OPTEE and ATF are built according to the SOC platform (t194 or t234), so it requires having hardware.nvidia-jetpack.som defined.
Changes include:
- Adding an ATF image with OPTEE and builtin nvluks-srv and hwkey-agent trusted applications that are flashed in the same per-device flash script.
- Adding the tee-supplicant service to each board running a TOS. This is used to broker communication between the REE and TEE (regular execution environment and trusted execution environment).
Tested on an Orin AGX devkit. Functionality between the nix-built TOS and stock TOS appears to be the same.
=> Add derivations for OPTEE and ATF

modules/default.nix, modules/devices.nix
Allows the user of this module to disable this functionality. Why do we need this instead of just using option priority? If the user sets fileSystems.* at a mkDefault level, then setting
fileSystems."/opt/nvidia/esp" at any level would override all other fileSystems, including "/".
Eval only
=> Add mountFirmwareEsp setting

samples.nix
This now appears to be working on Jetpack 5.1.1. Release notes for Jetpack 5.1.1 say it includes VPI2 fixes.
Closes #44
Tested on a Xavier AGX
=> Re-enable VPI2 test

README.md, flash-tools.nix, modules/flash-script.nix, ota-utils/ota-apply-capsule-update.sh
Add option to enable automatically applying firmware updates after `nixos-rebuild boot/switch` using the UEFI Capsule update mechanism.
To enable, set  `hardware.nvidia-jetpack.bootloader.autoUpdate = true;` and use systemd-boot as your bootloader.   (This could potentially work with other bootloaders, but systemd-boot provides `extraInstallCommands` we use)
Tested working on Xavier AGX devkit
=> Automatic Firmware updates

flash-tools-secureboot.patch, flash-tools.nix, flash-tools.patch
These fixes appear to be necessary to use the flashing script with firmware signing keys.
Tested by flashing an Orin Nano with `-u <pkc.pem>` cmdline option.
=> Add fixes for firmware signing

modules/flash-script.nix, ota-utils/ota_helpers.func
Set OTA relavent EFI variagbles if doing bootloader autoUpdate, so previous generations that don't yet have the systemd service can update.
Tested on a Xavier AGX
=> Run ota-setup-efivars as part of bootloader.autoUpdate

default.nix, modules/default.nix, modules/devices.nix
This adds support for the "Orin Nano".  At least from the flashing scripts perspective, it is basically the same as an Orin NX.  (Or rather, an Orin NX is the same as an Orin Nano).
Closes #76 
Tested by booting on an Orin Nano + devkit
=> Add Orin Nano

README.md, default.nix, device-pkgs.nix, flash-script.nix, modules/flash-script.nix, optee.nix
A number of cleanups and initial work on supporting NVIDIA's firmware secureboot implementation, described here:
https://docs.nvidia.com/jetson/archives/r35.3.1/DeveloperGuide/text/SD/Security/SecureBoot.html
Just tested that some existing NixOS closures still build
=> Initial work on secureboot

uefi-firmware.nix
This brings in https://github.com/NVIDIA/edk2-nvidia/commit/2c81e0fc74f703012dd3b2f18da5be256e142fe3, which allows for the Xavier AGX to have similar behavior to other boards in regards to the secure boot UEFI menu.
Manually tested on an Xavier AGX
=> Bump edk2-nvidia

modules/flash-script.nix
We were still referring to `bootloader.autoUpdate` instead of the new `firmware.autoUpdate` option.
Eval-only
=> Fix deprecation warning by using firmware.autoUpdate

device-pkgs.nix, flash-script.nix, modules/flash-script.nix, uefi-default-keys.dts
Nvidia's flash script allows for enrolling the following UEFI protected variables:
- `dbDefault`
- `kekDefault`
- `pkDefault`
These changes take their BSP script `tools/gen_uefi_default_keys_dts.sh` to create a DTBO for use during the flashing procedure.
Tested on an Xavier AGX. After flashing with these changes, Nvidia's EnrollFromDefaultKeysApp UEFI application picks up the default keys and enrolls them as PK, KEK, db, etc. on first boot.
=> Add NixOS options for enrolling default secureboot keys

device-pkgs.nix
Don't pass invalid argument requiredSystemFeatures as this is no longer an argument to this function.
=> Don't pass invalid argument requiredSystemFeatures

modules/flash-script.nix
Split Orin NX and Orin Nano variants. This will make it so the signedFirmware and bup packages only depend on the variants that correspond to the set hardware.nvidia-jetpack.som.
`nix flake check` only
=> Split Orin NX and Orin Nano variants

modules/devices.nix
Nvpmodel does not start properly unless using the nvpmodel config that matches the name of the board's device-tree `compatible` field.
Tested on an orin nano devkit
=> Use correct nvpmodel config for the orin nano devkit

default.nix
Nvidia's documentation provides instructions for downloading a GCC 9 toolchain, so we can do the same here.
Fixes #96 
Tested on an orin-agx-devkit.
=> Pin optee toolchain to GCC 9

device-pkgs.nix, modules/flash-script.nix, uefi-firmware.nix
The DER format of the public certificate can just be created at build-time based on the PEM-formatted trustedPublicCertPemFile. Since these are supposed to be the same certificate, it's less confusing if there's just one option for it.
Also, don't set default null 
Tested by performing a UEFI capsule update on the Orin nano devkit.
=> Remove publicCertificateDerFile and just use trustedPublicCertPemFile

device-pkgs.nix
Expose mkFlashScript from device-pkgs.nix. Thus one can now call devicePkgsFromNixosConfig from another package/flake, and get an attribute set where mkFlashScript is available. This makes it easier to create custom flash scripts, because not all the arguments need to be specified, but user of jetpack-nixos could just override the desired arguments, and use the defaults for others.
Tested from other project, using AGX Orin Devkit. This change does not really change any behavior in this project, but merely exposes one part of the API
=> Expose mkFlashScript from device-pkgs

0002-Exit-with-non-zero-status-code-on-TEEC_InvokeCommand.patch, optee.nix
The patch makes sure that nvluks-srv-app exits with a non-zero exit code when it encounters a TEE invoke error. This makes nvluks-srv-app more consistent with the rest of the failure modes of the program.
Tested on an xavier-agx-devkit.
=> Add patch for nvluks-srv-app

tegra-eeprom-tool.nix
This removes the dependence on fork patches.
=> Bump tegra-eeprom-tool to upstream master

device-pkgs.nix, modules/flash-script.nix
Add `additionalDtbOverlays` option, which is list of paths to compiled .dtbo files to include with the UEFI image while flashing. These overlays are applied by UEFI at runtime.  This is a NixOS module option that can be set as an alternative to setting the ADDITIONAL_DTB_OVERLAYS environment variable when running the flash script.
Tested that I can apply a device tree overlay to UEFI at runtime
=> Added additionalDtbOverlays option

uefi-firmware.nix
When all serial ports are disabled on a T194 device via a DTB overlay to the UEFI DTB, many EFI configuration tables end up missing (e.g. SMBIOS). This patch enables other configuration tables to still be setup properly in this scenario.
Tested on an xavier agx with all serial ports disabled in UEFI device tree.
=> Add patch for fixing missing EFI configuration tables on T194

kernel/0001-bpf-Generate-BTF_KIND_FLOAT-when-linking-vmlinux.patch, kernel/0002-kbuild-Quote-OBJCOPY-var-to-avoid-a-pahole-call-brea.patch, kernel/0003-kbuild-skip-per-CPU-BTF-generation-for-pahole-v1.18-.patch, kernel/0004-kbuild-Unify-options-for-BTF-generation-for-vmlinux-.patch, kernel/0005-kbuild-Add-skip_encoding_btf_enum64-option-to-pahole.patch, kernel/0006-tools-resolve_btfids-Warn-when-having-multiple-IDs-f.patch, kernel/default.nix
Removed build workaround where I disabled  `CONFIG_DEBUG_INFO_BTF`.
Booted kernel on Orin AGX devkit. Noted that `/sys/kernel/btf/vmlinux` exists.
=> Fix kernel issues preventing inclusion of BTF info

ota-utils/default.nix
On my system I’m having the setup-efi-vars unit fail because `bash` is not in the ambient environment (for whatever reason, but that seems like it ought to be otherwise supported anyway.)
Running `patchShebangs` will adjust these with specific references to the interpreter (which has an additonal bonus of maintaining a proper gc reference on the interpreter in question as well)
I built the `.#otaUtils` and inspected the binaries within to ensure that the outputs now have exact `/nix/store` references for the interpreter.
=> otaUtils: patchShebangs

kernel/default.nix
Workaround issue https://github.com/anduril/jetpack-nixos/issues/118 by disabling tegra-se for now. This shifts encryption/decryption for LUKS onto the CPU instead of the security engine (SE), so we lose the performance benefits of offloading this computation onto the SE.
Tested that `luksOpen` with `--perf-no_read_workqueue` and  `--perf-no_write_workqueue` would cause kernel panics on an Orin AGX before this PR--and that those kernel panics do not occur after this PR.
=> kernel: disable tegra-se since it broke LUKS

flash-tools.nix
NVIDIA has released these overlays fixing a couple of issues. From their release notes:
- Overlay which fixes a bug related to UART receiving data in the L4T 35.3.1 release.
- This patch fixes an issue with booting Jetson module in an environment with temperature below -20 degree centigrade.
Tested flashing and booting works on Orin NX + devkit, and that the USB firmware is now running version 80.05 instead of 80.03
=> Add additional BSP overlays for L4T35.3.1

board-automation.nix, board-automation.patch
- Added patch file to make `boardctl` compatible with Python 3
- Modified `board-automation` derivation to apply the patch and remove the `python2` dependency
```
nix shell github:evenfowler/jetpack-nixos/7ea7eb5a633dfe64f7f2947f91caf2a972d11590#board-automation
boardctl -t topo recovery
```
=> Remove python2 requirement for boardctl

default.nix, device-pkgs.nix, modules/default.nix, modules/flash-script.nix, optee.nix
These changes add a NixOS option for customizing the TEE_CLIENT_LOAD_PATH for tee-supplicant. Also added is a NixOS option for adding command-line arguments to tee-supplicant, helpful in this case for changing tee-supplicant's `--ta-dir`, the subdirectory under the load path where tee-supplicant will look for TAs. The default load path is set to "/var/lib/optee", but can trivially be changed to some static path built with nix. For example:
```nix
{ pkgs, ... }: {
hardware.nvidia-jetpack.firmare.optee.clientLoadPath = pkgs.linkFarm "optee-load-path" [{
name = "optee_armtz/my.ta";
path = taDerivation;
}];
}
``` 
where `taDerivation` is the path to the trusted application.
Fixes #100 
Tested on an orin-agx-devkit.
=> Build tee-supplicant with a customizable TEE_CLIENT_LOAD_PATH

edk2-openssl-patches.nix, uefi-firmware.nix
Updated edk2's in-tree OpenSSL version to 1.1.1t, to reflect the changes in nixos-23.05.
Created the list of patches to update the edk2-tree build system to support version 1.1.1t. Added few probably unnecessary patches to keep the chain of patches consistent with upstream tianocore/edk2. This basically contains all the pathes reagarding the OpensslLib directory up to https://github.com/tianocore/edk2/tree/edk2-stable202305 , but not the last one. 
Build & Flashed & Tested with AGX Orin devkit. Boots to NixOS nicely.
NOTE: I didn't specifically test any cryptographical functions (eg. SecureBoot), so please test those!
=> UEFI: update edk2 in-tree OpenSSL version to 1.1.1t

0001-Don-t-prepend-foo-bar-baz-to-TEEC_LOAD_PATH.patch, optee.nix
This is to supplement PR #103 
* By default, tee-supplicant prepends "/foo:/bar::/baz" into the TEEC_LOAD_PATH. Add a patch which removes that.
* Export buildOpteeTaDevKit to make it easier to build TAs in other flakes
AGX devkit and NX devkit
=> Don't add TEEC_TEST_LOAD_PATH into TA search paths

default.nix, device-pkgs.nix, optee.nix
The TA dev kit is specific per-board and it is necessary for this to be
exposed in order for users to build trusted applications that don't get
built into the OPTEE image.
This can be used when building a TA by using the make flag
"TA_DEV_KIT_DIR=${config.system.build.jetsonDevicePkgs.taDevKit}/export-ta_arm64".
Ensured `taDevKit` builds on a nixos system closure for an orin-agx-devkit
=> Expose `taDevKit` in `config.system.build.jetsonDevicePkgs.taDevKit`

modules/flash-script.nix, modules/uefi-boot-order.dts
This change adds a nixos option for changing the default boot order. The option defaults to using the same boot order from
https://github.com/NVIDIA/edk2-nvidia/blob/71fc2f6de48f3e9f01214b4e9464dd03620b876b/Silicon/NVIDIA/Tegra/DeviceTree/L4TConfiguration.dts, which gets applied in the flash script using `additionalDtbOverlays`.
Tested on an orin agx devkit
=> Add option for changing boot order

device-pkgs/default.nix, pkgs/flash-tools/default.nix
The flash scripts are typically run on machines where openssl 1.1 is expected. While this doesn't apparently have any functional difference for the standard usage in the flashing scripts, it may affect certain aspects when making modifications to support alternative signing methods.
Built and flashed on a Xavier NX devkit.
=> Switch flash scripts from openssl to openssl_1_1

default.nix, device-pkgs/default.nix, device-pkgs/flashcmd-script.nix, modules/flash-script.nix
If there is only a single jetson variant, we can produce a flash script
that doesn't need to detect the variant befor flashing. This can make it
so we don't need access to signing keys when performing the flashing
step. (They could, for instance, be available via `extra-sandbox-paths`
on the Nix builder machine.
Using this feature does, however, require specifying the variant
(boardsku, etc.) in the NixOS configuration, which is not always
immediately obvious.
Additionally, adds a new option `preSignCommands` which can be used to
set up the environment to enable the signature part to work.
Flashed a Xavier AGX devkit using a single-variant flash script
=> Add single-variant flash script capability

device-pkgs/default.nix
The `initrdFlash` script was not correctly running the output of `mkRcmBootScript`, as noted by @johnrichardrinehart in https://github.com/anduril/jetpack-nixos/pull/147. `mkRcmBootScript` should just output text to match what is done by `mkFlashScript`
Ran initrdFlash script against xavier-agx-devkit
=> Fix initrdFlash script

modules/devices.nix
With commit
https://github.com/nixos/nixpkgs/commit/5176a4f11356a338331d82e63563f8510b67317d, the option `fileSystems.<name>.options` will contain an "x-systemd.makefs". Since systemd-makefs does not take any parameters (but has sane defaults and actually uses fat32 for vfat fstype), the `formatOptions` option was made internal only and set to null. Let's set it null here unless systemd-makefs is not being used.
Fixes #105 
Tested that the assertion https://github.com/NixOS/nixpkgs/blob/28562b6c75906da822189e6f93bf45768dc04ee6/nixos/modules/tasks/filesystems.nix#L323 does not fail when evaluating a nixos config (using nixpkgs/nixos-unstable) with som xavier-agx and mountFirmwareEsp set to true. Also tested with nixpkgs/nixos-23.05 that formatOptions is a string with the value "-F 32 -n …
=> Don't apply formatOptions unless systemd-makefs is not being used

kernel/default.nix
The `CRYPTO_DEV_TEGRA_SE_USE_HOST1X_INTERFACE` option has a typo so it ends up not working. This PR changes it to the correct name
After the fix, LUKS filesystem no longer exhibits the `free cmd buf` error
=> Fixed crypto engine option typo

modules/devices.nix
It appears that the top-level `config` attribute cannot exist for the submodule `fileSystems.<name>`. Fix configuring this mount by removing that attribute.
It appears that the top-level `config` attribute cannot exist for the submodule `fileSystems.<name>`. Fix configuring this mount by removing that attribute.
Successfully build `config.system.build.toplevel` for a nixos config for an xavier-agx board.
=> Fix configuring secondary ESP on xavier-agx

kernel/0001-bpf-Generate-BTF_KIND_FLOAT-when-linking-vmlinux.patch, kernel/0002-kbuild-Quote-OBJCOPY-var-to-avoid-a-pahole-call-brea.patch, kernel/0003-kbuild-skip-per-CPU-BTF-generation-for-pahole-v1.18-.patch, kernel/0004-kbuild-Unify-options-for-BTF-generation-for-vmlinux-.patch, kernel/0005-kbuild-Add-skip_encoding_btf_enum64-option-to-pahole.patch, kernel/0006-tools-resolve_btfids-Warn-when-having-multiple-IDs-f.patch, kernel/0007-net-phy-realtek-read-actual-speed-on-rtl8211f-to-det.patch, kernel/0008-Lower-priority-of-tegra-se-crypto.patch, kernel/default.nix
Switched from disabling the tegra-se kernel module to lowering priority of the tegra-se crypto.  nvpmodel fails on certain devices if it cannot set the frequency of the se engine--which is exposed by the kernel module.
Tested LUKS encryption works on all device types.
=> Lower priority of tegra-se crypto modules

pkgs/uefi-firmware/default.nix, pkgs/uefi-firmware/edk2-openssl-patches.nix
Create and use `fetchgitpatch` instead of  `fetchpatch2`.  Like `fetchpatch2`, `fetchgitpatch` saves the "git extended headers", except it filters out  "index" lines that may change based on what Github outputs for us.
Done as an alternative to https://github.com/anduril/jetpack-nixos/pull/157.
Built `uefi-firmware`
=> Switch fetchpatch2 to "fetchgitpatch"

default.nix, device-pkgs/default.nix, modules/default.nix, modules/flash-script.nix, pkgs/optee/default.nix
Add a patch for specifying TA load path and plugin load path at the time of running tee-supplicant instead of being fixed at compile time. Also moves `opteeClient` out of `jetsonDevicePkgs` as it is not a board-specific package.
Based on changes from https://github.com/OP-TEE/optee_client/pull/365.
Tested on an orin-agx-devkit with the hello_world TA and syslog plugin from https://github.com/linaro-swg/optee_examples.
=> Use CLI flags for tee-supplicant load paths

pkgs/uefi-firmware/default.nix
uefi-firmware stopped building with NixOS 23.11, as util-linux (which includes libuuid) was removed from the depsBuildBuild of the edk2-package. Add libuuid to the depsBuildBuild, which then fixes the issue related to `-luuid`.
Tested by flashing on Orin AGX and Orin NX. Tested that the build works against NixOS 22.05, 23.05 and 23.11
=> uefi-firmware: fix edk2 build against NixOS 23.11

modules/default.nix, pkgs/l4t/default.nix
The initial motivation is for future support of `cuda_compat`. `cuda_compat` needs to take precedence over the current driver. It is achieved in https://github.com/NixOS/nixpkgs/pull/267247 by prepending the right path to CUDA libraries' `DT_RUNPATH`, so that `libcuda.so` is searched in `cuda_compat` first.
However, jetpack-nixos currently sets `LD_LIBRARY_PATH` to `/run/opengl-driver`. This prevent the Nixpkgs `cuda_compat` PR to work, because `LD_LIBRARY_PATH` takes precedence over `DT_RUNPATH`. Beside `cuda_compat`, it's probably best to not set `LD_LIBRARY_PATH` if we can avoid it, as it short-circuits most of other dynamic libraries loading mechanisms.
A comment in jetpack-nixos mentions that setting `LD_LIBRARY_PATH` is required for `libGLX_nvidia.so.0` to work (or to not complain). …
=> Don't set LD_LIBRARY_PATH

pkgs/ota-utils/default.nix
patchShebangs does not seem to update shebang-lines for some reason.
The ota-utils' systemd service scripts now have proper shebangs. The patchShebangs didn't patch them for some reason.
I tested this relatively small change on Orin AGX and Orin NX using cross-compilation.
=> ota-utils: Fix cross-compilation

modules/default.nix, modules/flash-script.nix
Add an `enable` option for tee-supplicant, but retain the current behavior of enabling it by default. This should remove some attack surface of devices that don't need tee-supplicant but have an optee instance running that is not configured to verify signatures of TAs at runtime. 
Also organize tee-supplicant related options into the `supplicant` attrset.
=> Allow for disabling tee-supplicant

modules/default.nix, modules/devices.nix
We were implicitly using the "null" value on the som and carrierBoard options as a way to specify that the values were unset and that jetpack-nixos should try to maximize compatibility acroos all types (with caveats that this may not always include all features). Now, we just have a separate "generic" value that we can use to represent this. It's easier to work with since we don't need to have "!= null" checks everywhere.
`nix flake check` for eval also ran internal graphics tests successfully .
=> Fix eval: Rework some option types to not be nullOr

flake.lock, flake.nix, pkgs/cuda-packages/default.nix
Bumped jetpack-nixos flake input to 23.11.
=> Bump jetpack-nixos nixpkgs flake input to 23.11 branch

kernel/0001-bpf-Generate-BTF_KIND_FLOAT-when-linking-vmlinux.patch, kernel/0002-kbuild-Quote-OBJCOPY-var-to-avoid-a-pahole-call-brea.patch, kernel/0003-kbuild-skip-per-CPU-BTF-generation-for-pahole-v1.18-.patch, kernel/0004-kbuild-Unify-options-for-BTF-generation-for-vmlinux-.patch, kernel/0005-kbuild-Add-skip_encoding_btf_enum64-option-to-pahole.patch, kernel/0006-tools-resolve_btfids-Warn-when-having-multiple-IDs-f.patch, kernel/0007-net-phy-realtek-read-actual-speed-on-rtl8211f-to-det.patch, kernel/0008-Lower-priority-of-tegra-se-crypto.patch, kernel/0009-bonding-gcc13-synchronize-bond_-a-t-lb_xmit-types.patch, kernel/default.nix
Fixes the compilation failure in #178 
Built the kernel, cross-compiled from `x86_64-linux`.
=> kernel: fix gcc 13 compilation failure

pkgs/uefi-firmware/default.nix
See CVE-2023-45229, CVE-2023-45230, CVE-2023-45231, CVE-2023-45232, CVE-2023-45233, CVE-2023-45234, CVE-2023-45235 and CVE-2022-36764.
Rundown on CVEs:
https://blog.quarkslab.com/pixiefail-nine-vulnerabilities-in-tianocores-edk-ii-ipv6-network-stack.html
Patches found from https://bugzilla.tianocore.org/show_bug.cgi?id=4518 and https://bugzilla.tianocore.org/show_bug.cgi?id=4118.
Tested netbooting on:
- orin-agx-devkit
- orin-nano-devkit
- xavier-agx-devkit
- xavier-nx-devkit
=> Provide patches for new networking vulnerabilities in EDK2

kernel/default.nix
Fixes a memory leak in kernel tegra serial driver.
This ensures the memory allocated in function `tegra_dma_prep_slave_sg`
is cleaned up properly. Manifested as slab unreclaimable growing unbounded
via calls to kmalloc-256
Tested on Xavier AGX custom carrier board
Ref: https://forums.developer.nvidia.com/t/serial-tegra-dma-driver-bug/258168/5
=> [kernel] Fix memory leak in kernel tegra serial driver

pkgs/l4t/default.nix, pkgs/samples/default.nix
Fix libnvmedia libraries dlopen() dependency on nvsci
Also adds a test to multimedia-test that reproduces the failure when this fix is not applied.
Failing test:
> Opening in BLOCKING MODE
> NvMMLiteOpen : Block : BlockType = 4
> ===== NVMEDIA: NVENC =====
> NvMMLiteBlockCreate : Block : BlockType = 4
> 875967048
> 842091865
> H264: Profile = 100, Level = 50
> NVMEDIA: Need to set EMC bandwidth : 846000
> NVMEDIA: Need to set EMC bandwidth : 846000
> NVMEDIA_ENC: bBlitMode is set to TRUE
> NvVideoEncTransferOutputBufferToBlock: DoWork failed line# 679
> NvVideoEnc: NvVideoEncTransferOutputBufferToBlock TransferBufferToBlock failed Line=690
> Could not read complete frame from input file
Succeeding test:
> Opening in BLOCKING MODE
> NvMMLiteOpen : Block : BlockType = 4
> ===== NVMEDIA: …
=> Fix libnvmedia libraries dlopen() dependency on nvsci

pkgs/l4t/default.nix
Recent update in repo https://github.com/OE4T/meta-tegra (this one OE4T/meta-tegra@b86c2ae) in fact breaks `jetpack-nixos` build:
```
hash mismatch in fixed-output derivation '/nix/store/n59rw7dri9dacvrav379m3i621qql6nf-0003-Update-conversion-defaults-to-match-NVIDIA-sources.patch.drv':
>          specified: sha256-vGilgHWinrKjX+ikHo0J20PL713+w+lv46dBgfdvsZM=
>             got:    sha256-6xCEjf432FLksCCk8+EpAbQU3PeGICOQ+6Q2OusUNa4=
```
I think we should refer all external repos by stable links to the certain commits instead of branches.
=> Stable link to OE4T/meta-tegra instead of master

modules/default.nix, pkgs/l4t/default.nix
Instead of hardcoding `/run/opengl-driver`, use `addOpenGLRunpath.driverLink`.
Booted on an orin-agx-devkit and ensured nvidia libraries still existed under `/run/opengl-driver`.
=> Use driverLink where possible

modules/default.nix, pkgs/containers/nvidia-ctk.nix
Updates nvidia-ctk since some patches were applied upstream. Also changes the systemd service to use RUNTIME_DIRECTORY (this is what upstream nixpkgs does when they call nvidia-ctk).
Tested on an orin-agx-devkit that running the l4t-jetpack container from nvidia still works with podman when passing `--device=nvidia.com/gpu=all`.
=> Update nvidia-ctk and use RUNTIME_DIRECTORY when calling nvidia-ctk

modules/devices.nix
The orin-nano and orin-nx SOMs have realtek NICs that take advantage of firmware that lives in the `linux-firmware` derivation. Instead of pulling in all of linux-firmware (1GiB+), just pull in what is needed for the `r8168` kernel module. Note that in Jetpack 35.3.1 the kernel module was called `r8169` and in Jetpack 35.4.1 the kernel module was changed to be `r8168`. This differs from mainline linux where the kernel module is `r8169`.
Tested on an orin-nano-devkit, ensured the initrd built with a config including `{ boot.initrd.kernelModules = [ "r8168" ]; }` includes the corresponding firmware in `lib/firmware/rtl_nic`. Also ensured that the warning message produced without this PR's changes no longer appears. The warning looks like this:
```
Starting systemd-udevd version 254.6
[ …
```
=> Add firmware needed for R816{8,9} network devices

UPGRADE_CHECKLIST.md, pkgs/l4t/default.nix
Programs which linked against both multimedia libs and libEGL_nvidia.so would end up with two versions of NvOsLibraryLoad and one of them would be used arbitrarily.
Now, we rename the symbols to have unique names to avoid the conflict.  This required a version of patchelf that is not yet in upstream nixpkgs.
As an additional note, this was discovered when runnig the video_cuda_enc sample, and debugged using LD_DEBUG=all + grepping for NvOsLibraryLoad and seeing that it was coming from the libnvos_multimedia lib.
Tested by running combined-samples on a Xavier AGX devkit
=> Further fix for NvOsLibraryLoad function calls

modules/devices.nix
Also don't use `linkFarm` to create the firmware derivations since that ends up requiring all of `linux-firmware` to exist in the nixos system's closure.
Tested on an orin-agx-devkit.
Before:
```
[   24.437081] rtw_8822ce 0001:01:00.0: Adding to iommu group 9
[   24.439144] rtw_8822ce 0001:01:00.0: Direct firmware load for rtw88/rtw8822c_fw.bin failed with error -2
[   24.439152] rtw_8822ce 0001:01:00.0: failed to request firmware
[   24.439182] rtw_8822ce 0001:01:00.0: Direct firmware load for rtw88/rtw8822c_wow_fw.bin failed with error -2
[   24.439184] rtw_8822ce 0001:01:00.0: failed to request firmware
[   24.441513] rtw_8822ce 0001:01:00.0: failed to load firmware
[   24.441515] rtw_8822ce 0001:01:00.0: failed to setup chip efuse info
[   24.441517] rtw_8822ce 0001:01:00.0: failed to …
```
=> Include wifi/bluetooth firmware wanted by orin-agx

modules/default.nix
Fixes booting a nixosConfiguration where `hardware.nvidia-jetpack.som = "generic";` on the Xavier NX (e.g. iso_minimal) by only enabling the efifb driver when the som is explicitly not xavier-nx or generic. Also found that the original issue does not affect the Xavier AGX variant so this PR also re-enables the efifb driver for the xavier-agx som.
=> fix: disable efifb driver for generic and only xavier-nx som types

modules/default.nix
Out of abundance of caution, disable efifb driver on all Xavier since root cause may not easily reproduce on all variants.
=> fix: disable efifb driver for all Xavier

modules/nvpmodel.nix
The `nvpmodel` service can fail to start due some files/devices under `/sys` not being writable early in boot. Simply setting `Restart="on-failure"` resolves the issue. Nvidia's upstream unit file only starts `nvpmodel` after the `nv` and `nvpower` services which likely delays the service a bit.
Allowing the service to restart gracefully successfully applies the power profile:
```
Jul 28 09:27:34 xavier-nx-emmc-quark-jp5 systemd[1]: Starting Set NVPModel power profile...
Jul 28 09:27:35 xavier-nx-emmc-quark-jp5 nvpmodel[886]: NVPM ERROR: Error opening /sys/devices/platform/c250000.i2c/i2c-7/7-0040/hwmon: 2
Jul 28 09:27:35 xavier-nx-emmc-quark-jp5 nvpmodel[886]: NVPM ERROR: failed to write PARAM VDDIN_OC_LIMIT: ARG WARN: PATH: /sys/devices/platform/c250000.i2c/i2c-7/7-0040/hwmon VAL: 4000 …
```
=> nvpmodel: restart on-failure

pkgs/l4t/default.nix, pkgs/samples/default.nix
No need to use fetchpatch for non-generated patches from a specific revision of another git repo.  Also, replace use of "master" with a pinned commit for another patch
Eval checks and built l4t-multimedia and multimedia-samples packages.
=> Fix incorrect fetches of patches

README.md, modules/flash-script.nix
Using systemd-boot is not a requirement for applying capsule updates. We can make the firmware update a systemd service, which gives us the behavior of running on every `switch-to-configuration` when the capsule update file changes.
Tested that the capsule update was successfully applied on an Orin AGX Devkit and a fused Xavier AGX Devkit.
=> Don't require using systemd-boot to get automated firmware updates

modules/devices.nix
The files in `linux-firmware` may vary depending on the nixpkgs version used, so we should allow for some files to be missing.
=> Be more forgiving on missing linux-firmware files

kernel/0009-Revert-random-use-static-branch-for-crng_ready.patch, kernel/default.nix
It's unclear the reason, but randomly, Xavier NX systems would crash immediately upon booting into the kernel. This would happen while initial entropy from the UEFI RNG table.  This appears to be working in 35.5.0, and this patch from the stable kernel is what is needed.
Tested booting a Xavier NX 10 times, and it succeeded every time.
=> kernel: add patch to fix Xavier NX crashes

kernel/0010-bonding-gcc13-synchronize-bond_-a-t-lb_xmit-types.patch, kernel/default.nix
This patch is needed to fix GCC 13 builds of the Linux kernel. This was mistakenly removed during the update to L4T 35.4.1.  Thanks @hacker1024 for pointing this out
Built the jetson kernel using `nixos-unstable` as of 2024-05-07
=> kernel: restore patch to fix gcc 13 compilation failure

modules/default.nix
A nixos config only needs a few things set in order to build correctly, `nixpkgs.hostPlatform` being one of them. In the case of jetson devices, we can at least provide a default value for this that gets people up and running with one less thing to set.
Tested building a nixos config for an orin-agx-devkit with the following config:
```nix
((builtins.getFlake "nixpkgs/nixos-unstable").lib.nixosSystem {
modules = [
{
boot.loader.systemd-boot.enable = true;
fileSystems."/".device = "/foo/bar";
}
{
imports = [
(builtins.getFlake "github:jmbaur/jetpack-nixos?ref=default-host-platform")
.nixosModules.default
];
hardware.nvidia-jetpack.enable = true;
hardware.nvidia-jetpack.som = "orin-agx";
hardware.nvidia-jetpack.carrierBoard = "devkit";
}
];
}).config.system.build.toplevel
```
=> Set a default host platform

pkgs/l4t/default.nix
Added nvidia-l4t-gstreamer package, which provides several GStreamer plugins.
Ran GStreamer pipeline with several NVidia plugins on AGX Orin:
```bash
gst-launch-1.0 videotestsrc ! video/x-raw,width=176,height=144 ! nvvidconv ! nvv4l2h264enc ! h264parse ! qtmux ! filesink location=a.mp4
```
=> Package l4t-gstreamer

UPGRADE_CHECKLIST.md, default.nix, pkgs/tests/default.nix
This test ensures that device passthrough to OCI containers works for the docker and podman runtime by using the `deviceQuery` tool NVIDIA ships source for in their l4t-jetpack image. It also tests for false- positives.
Tested on an orin-agx-devkit and xavier-agx-devkit with both docker and podman enabled at the same time (docker version 25.0.0)
=> Add simple OCI test

modules/default.nix
We should prevent colliding priorities with configs that have `nixpkgs.hostPlatform` set from the output of `nixos-generate-config`.
N/A
=> Change priority of `nixpkgs.hostPlatform`

pkgs/containers/nvidia-ctk.nix
Updates nvidia-ctk to the next non-RC release
Tested OCI functionality on an orin-agx-devkit and xavier-agx-devkit
=> Bump nvidia-ctk to 1.15

pkgs/optee/default.nix
OPTEE and related projects should build in seconds, not minutes.
Tested that the nvluks TA still functions properly on an orin-agx-devkit and xavier-agx-devkit
=> Build OPTEE firmware with enableParallelBuilding

modules/devices.nix
Some files in linux-firmware are symlinks, so when we extract them into a smaller derivation, we should retain the same filename to ensure a driver needing firmware is able to find the right file. The `install` tool will dereference the symlink and use the symlink's basename to ensure we get the right content at the right location.
Tested building a nixos config's `config.hardware.firmware` for an orin-nx and confirmed that all the correct rtl nic firmware was present
=> Retain linux-firmware basename

flake.lock, flake.nix, pkgs/samples/default.nix
Bumps flake.nix to NixOS 24.05
Tested by `nix flake check` and running all internal automated device tests. (boot, flash, samples, etc)
=> Bump to NixOS 24.05

device-pkgs/default.nix, modules/flash-script.nix, overlay-with-config.nix
The standard flash.sh script would successfully flash the device, however, the single variant flash script and the initrd-based flash scripts would not.  This was due to not setting various necessary environment variables.
Tested both flash scripts and booted Orin AGX Industrial on a devkit.
=> Fix flashing Orin AGX Industrial variant

device-pkgs/flash-script.nix, overlay-with-config.nix
Fixed fuse script build error:
```
… while calling the 'derivationStrict' builtin
at /builtin/derivation.nix:9:12: (source not available)
… while evaluating derivation 'write-pulsar-nx-fuse'
whose name attribute is located at /nix/store/gxzsyp45pxvwk5yj4q9sdb6rrndyfc1z-source/pkgs/stdenv/generic/make-derivation.nix:348:7
… while evaluating attribute 'text' of derivation 'write-pulsar-nx-fuse'
at /nix/store/gxzsyp45pxvwk5yj4q9sdb6rrndyfc1z-source/pkgs/build-support/trivial-builders/default.nix:148:16:
147|     runCommand name
148|       { inherit text executable checkPhase allowSubstitutes preferLocalBuild;
|                ^
149|         passAsFile = [ "text" ];
(stack trace truncated; use '--show-trace' to show the full trace)
error: cannot coerce a function to a string
```
With this …
=> Fixed fuse script build error

device-pkgs/flash-script.nix, modules/default.nix, modules/flash-script.nix
`mdDoc` is no longer used in upstream Nixpkgs as of 24.05.
`nix flake check --system aarch64-linux` passes.
=> Remove uses of lib.mdDoc

pkgs/l4t/default.nix
There's a bug in the multimedia API sample classes that leads to a segmentation fault in a few cases when using a non-Debian glibc.
The PR adds [OE4T's patch](https://github.com/OE4T/meta-tegra/blob/master/recipes-multimedia/argus/tegra-mmapi-samples/0004-samples-classes-fix-a-data-race-in-shutting-down-deq.patch) to fix the issue.
=> l4t-multimedia: Fix a data race in shutting down dequeue thread

pkgs/flash-tools/default.nix
Since we aren't always using flash-tools on x86_64-linux, using pre-built dtc and fdtoverlay doesn't always work. We should prefer the dtc package that we provide with nix over the pre-built ones nvidia provides.
There aren't actually that many pre-built binaries, and these appear to be the only ones that are otherwise available through nixpkgs:
```
$ fd --type executable . ./result-bspSrc --exec file {} \; | rg ELF
./result/tools/ota_tools/version_upgrade/nv_kernel_bootctrl_generator: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, for GNU/Linux 2.6.8, BuildID[sha1]=b4e95940fbcb81d1e276a8d19b5db920ddb8ae40, with debug_info, not stripped
./result/tools/dcb_tool/dcb_tool: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter …
```
=> Remove pre-built dtc binaries

overlay.nix, pkgs/cuda-packages/default.nix, pkgs/samples/default.nix
Updates all references of `cudaPackages.autoAddOpenGLRunpathHook` to `autoAddDriverRunpath`. See https://github.com/NixOS/nixpkgs/issues/141803.
=> cudaPackages.autoAddOpenGLRunpathHook -> autoAddDriverRunpath

pkgs/l4t/default.nix, pkgs/samples/default.nix
This library is needed for runtime PTX compilation. It's unclear why NVIDIA has this library in l4t-3d-core and not in l4t-cuda. Even more so since the cuda compat package has libcuda as well as libnvidia-ptxjitcompiler in the same package. meta-tegra does a similar thing where they pull libnvidia-ptxjitcompiler out of l4t-3d-core and place it in the same package as libcuda.
Additionally, add matrixMul* samples, including matrixMulDynlinkJIT specifically, which was failing to run previously.
Fixes #184 
Tested matrixMulDynlinkJIT sample now runs on an Orin AGX devkit
=> Move libnvidia-ptxjitcompiler library into l4t-cuda

pkgs/cuda-packages/default.nix, pkgs/samples/default.nix
CUPTI was not working because it was lacking an RPATH entry that would ensure it can load libraries in the same directory (e.g. libnvperf_host.so).
Tested by running CUPTI samples on Orin AGX devkit and Xavier AGX devkit
=> Fix libcupti RPATH and add CUPTI samples

pkgs/l4t/default.nix
The nv_fuse_read.sh shell script (in `l4t-tools`) expects `bc` to be in PATH.
Tested on a fused xavier-agx and an unfused orin-agx.
=> Add bc to nv_fuse_read.sh path

device-pkgs/default.nix, modules/flash-script.nix, overlay-with-config.nix
`preSignCommands` is used in two different contexts, when building derivations that are using the package-set defined in the NixOS config for a machine (defaults to a native aarch64-linux package-set) and when building flash scripts (defaults to a native x86_64-linux package-set). In order to support the use-case of using nix outputs obtained from a package-set within `preSignCommands`, the value set in this option must not carry in any output paths from package-sets defined elsewhere. For example, the following configuration is problematic and will not work when building the flash script, due to `pkgs` having a `hostPlatform` of aarch64-linux, thus `hello` will be an ELF binary targeting aarch64-linux:
```nix
{ pkgs, ... }: {
hardware.nvidia-jetpack.firmware.secureBoot.preSignCommands = …
```
=> Allow accessing correct `pkgs` during `preSignCommands`

README.md, modules/default.nix
This option is not yet compatible with Jetson devices.
Tested as in https://github.com/NixOS/nixpkgs/issues/344729. Also tested assertion is hit if we enable `hardware.nvidia-container-toolkit.enable`.
=> Prevent usage of hardware.nvidia-container-toolkit.enable

modules/default.nix
Added console.enable option to allow for disabling the default console boot kernelParams
=> Add console.enable option to modules/default.nix

modules/devices.nix, modules/flash-script.nix
The NixOS modules at `<jetpack-nixos>/modules/{flash-script.nix,devices.nix}` should not do anything unless `hardware.nvidia-jetpack.enable` is `true`.
Ensured behavior in these modules is still active on jetson devices (and no longer active on non-jetsons).
=> Ensure modules behavior is gated by enable option

device-pkgs/default.nix, device-pkgs/flash-tools-flashcmd.nix, modules/flash-script.nix, overlay-with-config.nix
This change adds more packages from `device-pkgs` into the overlay that contributes to the system's package-set. The packages moved over in this change are notably ones that have the `requiredSystemFeatures` attribute. This means that we could eventually remove the `requiredSystemFeatures` option and let users change the derivation how they need in their own overlay.
Tested flash, initrd flash, UEFI capsule update, and basic boot test on an orin-agx-devkit and a fused xavier-agx-devkit
=> Move more packages into the overlay

device-pkgs/default.nix, overlay-with-config.nix, pkgs/uefi-firmware/default.nix
Including the DTBO used for configuring the boot order in the initrd flash script means that the temporary edk2 build used only for flashing has the possibility of booting from something other than the kernel/initrd meant for flashing. Excluding this DTBO when performing the initrd flash method means that this is no longer possible.
Tested on an xavier-agx-devkit that was previously netbooting when attempting to use the initrd flash script.
=> Ensure declarative boot order doesn't influence initrd flash script

pkgs/flash-tools/default.nix
Since lz4/lz4@65998fe,
the lz4c symlink no longer exists, but is wanted by `flash.sh`. The
`lz4` program adds a set of legacy cmdline flags when `argv[0]` is
`lz4c` (see https://github.com/lz4/lz4/blob/6cf42afbea04c9ea6a704523aead273715001330/programs/lz4cli.c#L444),
however NVIDIA doesn't use any of these legacy flags in `flash.sh`, they
only require the `lz4c` program to be in PATH.
Building the `bup` derivation for an orin-agx-devkit no longer fails using a nixpkgs rev from the nixos-24.11 release.
=> flash-tools: add back missing lz4c program

pkgs/uefi-firmware/default.nix
Fixes #258.
Previously, `nix build github:anduril/jetpack-nixos#flash-orin-nano-devkit` would fail with one of:
```
[2/0/5 built] building CVE-2023-45229_CVE-2023-45230_CVE-2023-45231_CVE-2023-45232_CVE-2023-45233_CVE-2023-45234_CVE-2023-45235.patch: Warning: Problem : HTTP error. Will retry in 3600 seconds. 3 retries left.
```
or
```
[2/0/5 built] building CVE-2022-36764.patch: Warning: Problem : HTTP error. Will retry in 3600 seconds. 3 retries left.
```
because EDK2 moved from using Bugzilla to GitHub issues. As a result they migrated all their attachments over to a new GitHub repo. More here: https://github.com/tianocore/edk2/discussions/6544
This PR simply changes the URL to the GitHub URLs for the same patches. The hashes aren't changed.
```
nix build …
```
=> fix: pull edk2 patches from github, rather than deprecated bugzilla urls

modules/default.nix, modules/flash-script.nix, overlay-with-config.nix, pkgs/l4t/default.nix
Minor cleanup that is in line with  https://github.com/anduril/jetpack-nixos/commit/6d30a91458f2de2a2987cc0eacbad64aa86da439 to rename the driver package
The package now compiles as part of the https://github.com/tiiuae/ghaf platform
=> Fix driver

pkgs/samples/default.nix
As far as I can see, this didn't actually ever require opencv2 specifically.  I belivee I just made a rookie mistake and assumed it did because the #include referred to <opencv2/...>.  However, it appears that even in opencv4 the includes are prefixed with opencv2/.
Built `multimedia-samples`, ran `multimedia-test` on a xavier-agx-devkit.
=> Use opencv4 for multimedia-samples

flake.lock, flake.nix
Update flake.nix to latest NixOS release
=> Bump nixpkgs to nixos-24.11

kernel/display-driver.nix
With the latest changes to gcc, introduced in gcc14 there conftest is failing. GCC14 is now part of the nixos-unstable so this is a preventative change and does not introduce a regression on gcc < 14.
do not enforce the strict checking of implicit-function-declaration
built against nixos-unstable
=> nv-display-driver: GCC14 fix implicit function

modules/flash-script.nix, overlay-with-config.nix, pkgs/ota-utils/default.nix, pkgs/ota-utils/ota-apply-capsule-update.sh, pkgs/ota-utils/ota_helpers.func
In 9cea389171151c28dab47dfc1b08401e87aabfa0, we broke the ability for using `nixos-rebuild boot` to apply capsule updates. This change adds that ability back. The systemd service is kept as we still want capsule updates to be applied in cases where a different bootloader is being used (or perhaps some other niche setup).
Manually tested on an xavier-agx-devkit:
- `nixos-rebuild boot` and `nixos-rebuild switch` installs the capsule update if no prior one exists
- `nixos-rebuild test` does nothing
=> Allow `nixos-rebuild boot` to work with automated firmware updates

overlay-with-config.nix
We must ensure we are using `flash-tools` for the build platform when we are using it during a build (i.e. not on a machine performing the flashing at "runtime").
This change fixes the immediate issue of some of the `packages` flake outputs not building (since we cross compile them), however there is some good future work that can be done to re-organize these derivations where we can just `callPackage` them and automatically get the right `flash-tools`.
Tested against internal test suite as well as tested the fixed flake outputs for uefi capsule updating and initrd flashing for an orin-nx devkit.
=> Fix platform firmware and UEFI capsule builds when cross compiling

pkgs/uefi-firmware/default.nix
Should fix a critical issue for AGX Xavier not accepting capsule updates after a few hundred reboots:
https://github.com/NVIDIA/edk2-nvidia/issues/114
Tested by building and applying the UEFI update on an AGX Xavier device.
=> uefi-firmware: bump edk2-nvidia to latest r35.6.0-updates branch

pkgs/uefi-firmware/default.nix
UEFI-firmware compile fails with "missing binary operator before token "("", because "__has_builtin"-operator is not defined within gcc 14. Patching edk2-sources with existing patch. Patch is fetched from NVIDIA EDK2 repo.
Fetched patch checks if  "__has_builtin"-operator has been defined and then uses it. Further information:
*  GNU CPP [documentation](https://gcc.gnu.org/onlinedocs/gcc-14.2.0/cpp/_005f_005fhas_005fbuiltin.html) about "__has_builtin"-operator.
* tianocore/edk2 [pull request](https://github.com/tianocore/edk2/pull/5781)
Compiled with gcc 14 and  gcc 13 and both compiles.
=> uefi-firmware: Fix GCC 14 compile issue

overlay.nix
The `nvidia-display-manager` is not actually `callPackage`d from the `kernelPackages` scope, meaning that changes to packages within the scope (like the kernel itself) are not used in the `nvidia-display-manager` derivation.
In particular, this means that when using options like [`boot.kernelPatches`](https://search.nixos.org/options?channel=unstable&show=boot.kernelPatches), `nvidia-display-manager` erroneously still references the stock kernel, leading to two kernels being built.
This MR fixes this.
=> Use kernelPackages scope for nvidia-display-driver callPackage

modules/flash-script.nix
Add `coreutils` to the `updateScript` for `cat` and `echo`.
```
updating systemd-boot from 256.7 to 257.2
Copied "/nix/store/2bxf2a2215zspixdmw03vyi31q098ij6-systemd-257.2/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/boot/EFI/systemd/systemd-bootaa64.efi".
Copied "/nix/store/2bxf2a2215zspixdmw03vyi31q098ij6-systemd-257.2/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/boot/EFI/BOOT/BOOTAA64.EFI".
Created EFI boot entry "Linux Boot Manager".
/nix/store/zv8x2rf4lx3fs8pdhpzdhx3wxysr8m6x-update-jetson-firmware/bin/update-jetson-firmware: line 25: cat: command not found
Failed to install bootloader
warning: error(s) occurred while switching to the new configuration
```
TODO:
=> modules: flash-script: Add coreutils to updateFirmware script

modules/flash-script.nix
Jetson 35.6 BSP "jetson_board_spec.cfg"-file uses/defines Orin AGX 64gb "300" as a fab value. 
Evaluates and compiles.
=> Orin AGX 64gb fab from "000" to "300"

pkgs/flash-from-device/default.nix
`pkgsStatic.mtdutils` fails to build natively in NixOS 24.11 due to the cmoka dependency not being found for package tests.  However, the cross-compiled static mtdutils _does_ build successfully due to the tests being disabled in that case upstream.  This leads to initrd flash scripts building in some cases, and others not, depending on if the NixOS system they're based on is cross-compiled or natively-compiled.  Concretely, the `initrd-flash-*` flake package outputs all currently work (since they are cross-compile firmware), but the `.config.system.build.initrdFlashScript` from a natively-built NixOS system does not.
Built the `initrdFlashScript` from a natively-built NixOS system.
=> flash-from-device: workaround build failure for mtdutils

kernel/default.nix
https://github.com/NixOS/nixpkgs/pull/366004 introduced a change that
warns and errors out when modules are defined and not acutally set for a
particular target.
This patch rectifies that by going back the the previous method of
ignoring those errors and not breaking the build. Commentary is left
inline to explain the situation and possible future solutions.
tested against orin agx target for ghaf.
there are similar solutions being deployed in nixpkgs to work around
this e.g.
https://github.com/NixOS/nixpkgs/pull/375165
=> unused module errors

modules/flash-script.nix
We should not attempt to perform a firmware update if the system is being virtualised (e.g. in make-disk-image.nix).
Fixes #276
Tested to work with the following expression:
```nix
let
jetpack-nixos = builtins.getFlake "github:jmbaur/jetpack-nixos/firmware-update-detect-virt";
nixpkgs = builtins.getFlake "github:nixos/nixpkgs/nixos-24.11";
in
(nixpkgs.lib.nixosSystem {
modules = [
(
{
config,
lib,
pkgs,
...
}:
{
imports = [ jetpack-nixos.nixosModules.default ];
fileSystems."/".device = "/dev/foo";
boot.loader.systemd-boot.enable = true;
hardware.nvidia-jetpack = {
enable = true;
som = "orin-agx";
carrierBoard = "devkit";
};
system.build.diskImage = import "${pkgs.path}/nixos/lib/make-disk-image.nix" {
inherit config lib pkgs;
label = "nixos";
format = "qcow2";
partitionTableType = "efi"; …
```
=> Skip firmware updates if script is run on a virtualised system

pkgs/flash-tools/default.nix
The qemu-user package is a much build-time dependency than the qemu package (~185MiB vs ~1.7GiB), and it contains everything we need in flash-tools.
Tested building a capsule update for an orin-agx-devkit (natively compiled, aarch64-linux build platform & aarch64-linux host platform), which tests the codepath where qemu-user is used.
=> flash-tools: use smaller qemu build-time dependency

device-pkgs/default.nix, modules/flash-script.nix, overlay-with-config.nix, pkgs/flash-tools/default.nix, pkgs/flash-tools/flash-tools.patch, pkgs/optee/default.nix
Jetpack 5.1.5 changed how RCM (recovery mode) booting happened, which broke Xavier AGX and any fused/securebooting device.   This PR fixes those two issues.
Tested initrdFlashScript on Xavier AGX and on a fused Orin Nano.
=> Fix initrd flash script with Jetpack 5.1.5

modules/default.nix
If booting off USB-C port, these drivers will be needed to detect the attached drive and configure the USB stack to act as host mode.
=> Add ucsi drivers to ramdisk for orin-agx-devkit

pkgs/cuda-packages/buildFromDebs.nix, pkgs/cuda-packages/deb-builder/fixup.nix, pkgs/l4t/default.nix
We had a few broken symlinks in cuda packages. The symlinks should only be created if the destination exists.
=> Fix broken symlinks

README.md, modules/flash-script.nix, overlay-with-config.nix, pkgs/optee/default.nix, pkgs/ota-utils/default.nix, pkgs/ota-utils/ota-check-firmware.sh, pkgs/uefi-firmware/default.nix
Currently, the version field we bake into the UEFI firmware is just the L4T version.  A simple version field does not any of the additional customizations (such as patches) we or the end-user may do on top of it. This makes it difficult to determine if the current firmware on a device includes the customizations expected.
Additionally, since the firmware autoupgrade feature keys off of the version number, a user has to know to manually apply a capsule update if they changed something that affects the platform firmware, which is not always obvious.
This adds a hash to the version field, like: `35.6.1-06cb4270ebfe`. Now, firmware should automatically be upgraded if there is a change that can affect platform firmware. This gets us a level of "congruence" similar to NixOS itself.  The …
=> uefi-firmware: update version to include unique hash

modules/flash-script.nix
There are many cases where we may want to "switch-to-configuration boot" a NixOS system with hardware.nvidia-jetpack.firmware.autoUpdate, but not apply the capsule update. This lets us control that at runtime, so we don't have to disable the `autoUpdate` option and then get a different system hash...
Manually ran a `switch-to-configuration boot` command with the `JETPACK_NIXOS_SKIP_CAPSULE_UPDATE` and noted that it skipped applying the update.
=> Skip capsule update if certain environment variable is set

modules/flash-script.nix
Otherwise, this will fail with:
```
line 16: JETPACK_NIXOS_SKIP_CAPSULE_UPDATE: unbound variable
```
I have never made a mistake, ever, in my life.
Booted a device, noticed the `firmware-update` service succeeds.
Still passed UEFI capsule update test still
=> Fix bashism

modules/flash-script.nix
Test should check if JETPACK_NIXOS_SKIP_CAPSULE_UPDATE is set.
-v varname returns True if the shell variable varname is set [1].
[1]: https://www.gnu.org/software/bash/manual/bash.html#Bash-Conditional-Expressions
=> fixup! Fix bashism

pkgs/flash-from-device/default.nix, pkgs/flash-from-device/flash-from-device.sh
- flash-from-device: Add patches to compile mtdutils with musl 
nixpkgs 25.05 bumped mtdutils to 2.3.0. This version had some
regressions in order to compile with musl.
- flash-from-device: Add missing fields from flash.idx
flash.idx contains a filesize field. We don't currently use this field
nor the fields after, but let's fix it since it was noticed.
=> Flash from device fixes for 25.05

pkgs/kernels/r36/default.nix
This package only contains t194 (Xavier) firmware under lib/firmware, which isn't relevant for Jetpack 6.  t234 (Orin) xusb firmware is included as another partition on the QSPI.
Tested by booting `orin-agx-devkit` and noting USB still worked
=> kernel: remove l4t-xusb-firmware from EXTRA_FIRMWARE_DIR

pkgs/flash-from-device/default.nix
The build failure popped up again, re-apply the workaround.
=> flash-from-device: Reapply workaround build failure for mtdutils

pkgs/samples/vpi-test.nix
Finish renaming "vpi2-test" as "vpi-test".
Fixes: 6c40cc625c83 ("cuda-packages: Build vpi2 for jetpack 5, vpi3 for jetpack 6")
=> vpi-test: Rename as "vpi-test"

modules/default.nix
Nvidia's jammy kernel has downstream apparmor patches which require "apparmor" to appear sufficiently early in the lsm= kernel parameter.
Add a mkBefore [ "apparmor" ] to ensure it's early in the list. This causes apparmor to appear twice in the list: once at the beginning from the mkBefore and once at the end (default). This doesn't appear to be a problem.
nixos-25.05 introduces a new security.lsm option which sets the lsm= kernel parameter. The current implementation doesn't guarantee that apparmor is first in the list. Note that upstream implementation of apparmor does not care whether it is first or last in the list, so this change is not suitable for upstream nixpkgs.
=> apparmor: Ensure lsm argument is sufficiently early in list

pkgs/kernels/r36/oot-modules.nix
If compiling an out-of-tree module which depends on nvidia-oot-modules, we need the sources (for headers) and Module.symvers for CRC symbol versioning. Export a concatenated Module.symvers in the dev output.
=> nvidia-oot-modules: Add dev output with combined Module.symvers

modules/default.nix
It doesn't make sense to do "Before" a socket. In my testing, this causes docker to never start.
Also, docker.enableNvidia is optional with the new container-toolkit.enable option. Just guard the before on Docker enabled.
=> CDI: don't add before docker.socket

README.md
Updated READ.me file. 
Under installing NixOS:
Added docs for using flake which consists of:
- Removing line under import from configuration.nix:
(builtins.fetchTarball "https://github.com/anduril/jetpack-nixos/archive/master.tar.gz" + "/modules/default.nix")
- And providing a template for flake.nix users.
Tested and works on Orin AGX with NixOS 25.05
=> docs: improved docs for flake users

pkgs/l4t/default.nix
Looks like upstream nixpkgs has the patchelfUnstable attribute that seems to be version 0.18.0. Don't think the in-line overriding of it is necessary if we used the upstream provided one?
Haven't tested this, as I'm assuming the hashes will change, but only because the `pname` will be different of patchelf. I don't expect functional changes.
=> l4t: use upstream patchelf

modules/flash-script.nix, overlay-with-config.nix, pkgs/optee/default.nix, pkgs/optee/remove-force-log-level.diff
Increasing/decreasing the log level is a convenient way to get more information from OP-TEE. Expose this optee configuration parameter as a NixOS option.
- hardware.nvidia-jetpack.firmware.optee.coreLogLevel
- hardware.nvidia-jetpack.firmware.optee.taLogLevel
=> optee: Allow specifying log level from NixOS option

README.md, modules/default.nix
Fixes incorrect use of `mkRenamedOptionModule`.
Updates the README to reflect changes to use of containers.
=> container fix and README update

pkgs/kernels/r36/oot-modules.nix
`l4t-oot-modules` does not build when using any nixpkgs past https://github.com/nixos/nixpkgs/commit/9f9b582 due to it inheriting the kernel make flags. If we set `__structuredAttrs` here as well, it will work regardless.
Tested `l4t-oot-modules` successfully builds before `9f9b582` as well as after `9f9b582`.
=> oot-modules: enable __structuredAttrs to handle flags with spaces

pkgs/kernels/r36/oot-modules.nix
This reverts commit 9e9de257556332811a0fd0e05559ea1627a80db2, reversing changes made to d9530d50b82b71c224046ce95c04d06cb218f297.
Fixes: anduril/jetpack-nixos#352
=> Revert "Merge pull request #351 from jmbaur/fix-l4t-oot-modules-master"

modules/flash-script.nix
Found `fab=401` and `boardrev=F.0` xavier-agx variant using OE4T tegra-eeprom-tool.
=> Add xavier-agx 2888-401-0004-F.0-1-2 variant

mk-overlay.nix
OP-TEE was originally pinned to use gcc 9 because that's what NVIDIA's toolchain was using by default.  GCC 9 has now been removed from nixpkgs.  This makes optee similar to our kernel and edk2 builds and just uses the default stdenv provided by nixpkgs.
Fixes: https://github.com/anduril/jetpack-nixos/issues/346
Tested booting and nvluks trusted app with JP5 and JP6 on Orin AGX and Orin Nano. Also tested JP5 on Xavier AGX.
=> optee: use default stdenv

pkgs/cuda-packages/cuda_cudart/fixup.nix
The stubs output allows packages to link against driver stubs.
As an example, upstream `llama-cpp` will fail in its `configurePhase` because it is unable to locate `CUDA::cuda_driver` (the `cuda_cudart` stubs).
=> cudaPackages.cuda_cudart: propagate stubs output by default

README.md, mk-overlay.nix, modules/default.nix
At the moment, a mixture of `config.boot.kernelPackages` and `pkgs.nvidia-jetpack.kernelPackages` is used throughout the NixOS module. This can lead to duplicate kernels being built when the former fixed point is modified separately to the latter (e.g. with the `boot.kernelPatches` option).
This PR moves everything to use `config.boot.kernelPackages` only, fixing this issue.
In order to keep allowing custom kernel package sets to be used ("Bring Your Own Kernel"), the `kernelPackagesOverlay` is no longer pre-applied in the overlay itself. This allows any package set (from `pkgs.nvidia-jetpack` or otherwise) to be combined with the overlay when being passed to `config.boot.kernelPackages`.
A fix for the `devicetree` `callPackage` like in #271 is also included.
=> Apply the kernelPackages overlay in the NixOS module, to use a single fixed point

pkgs/l4t/default.nix
The patchelfUnstable that is being picked up is the aarch64 version which can not run on an x86_64 system, unless binfmt is enabled.
```
/nix/store/i5j0b0x9vvzwgbj3ydk14hp2rqc4lll7-stdenv-linux/setup: line 318: /nix/store/l9zagx3fyg26amzxhzjg51dshzv11kk6-patchelf-aarch64-unknown-linux-gnu-0.18.0-unstable-2025-08-13/bin/patchelf: cannot execute binary file: Exec format error
```
So ensure that the build system package is being used for patchelfUnstable.
Fixed cross-compilation issue
build a cross compiled image on an x86 machine that does not have binfmt enabled.
=> fix cross compile patchelfUnstable

pkgs/kernels/r36/oot-modules.nix
Fix Jetpack 6 build of oot-modules when `hardware.nvidia-jetpack.kernel.realtime = true;`.
Fixes https://github.com/anduril/jetpack-nixos/issues/363
Booted an Orin AGX devkit and ran samples test.
=> l4t-oot-modules: ignore PREEMPT_RT check
