anduril/jetpack-nixos

kernel/default.nix

The kernel build was failing with:
```
dtc: livetree.c:438: propval_cell: Assertion `prop->val.len == sizeof(cell_t)' failed.
```
This was due to certain device tree overlay files with "remote-endpoint" nodes that referred to a string instead of a phandle. For now, we'll just remove those files.
Fixes #1

Fix kernel not building in NixOS 22.11

---

modules/devices.nix

Booting the installation ISO wasn't working consistently on Xavier NXs, with the Linux kernel crashing immediately on some NXs. Flashing with the upstream SDK script appeared to fix it, and the only substantive difference between our flash scripts and upstream's is that we weren't flashing the emmc/sd card, just the SPI.

Flash sd card or emmc for Xavier NXs

---

board-automation.nix
default.nix
flake.nix

This PR packages the build_automation scripts into their own package.
Basic functionality for `boardctl` and `nvtopo.py` were tested against an Orin AGX developer kit and confirmed to work.

Package board-automation scripts

---

default.nix
flake.nix
python-jetson.nix

This adds a package definition for [python-jetson](https://github.com/NVIDIA/python-jetson)
This package has been tested against a Jetson AGX Xavier devkit

Add python-jetson package

---

samples.nix

This PR adds a set of simple scripts which test the NVIDIA samples for cuda/tensorrt/etc. These should be run to smoke-test a Jetpack release, or when refactoring the corresponding packages.
When this is merged, you can run this on your device easily via `nix run github:anduril/jetpack-nixos#samples.combined-test`
Tested the combined-test script on Orin AGX and Xavier AGX.

Add test scripts to exercise nvidia samples

---

cuda-packages.nix
flake.nix

Added nsight_system_host(x86_64) and nsight_system_target
Tested that nsight_system_host can open a report file generated by nsight_system_target 
Image of nsight_system_host analysis:

Added  nsight_system

---

cuda-packages.nix
flake.nix

Added nsight compute host and target
Collected data using ncu and ncu-ui successfully parsed it

Package nsight compute

---

jetson-firmware.nix

Avoid recompilation of imagemagick for bootlogo

---

default.nix

Fix evaluation error when building realtime kernel
Eval-only.

Fix evaluation error when building realtime kernel

---

flash-from-device.nix

This was missed in the big PR
Automated testing for all 4 variants.

Fix for flash-from-device script not working

---

device-pkgs.nix
optee.nix
ota-utils/ota_helpers.func

Recent PRs broke initrd-based flashing. This should fix it.
Tested on all 4 supported variants.

Fix initrd-flash scripts

---

cuda-packages.nix
device-pkgs.nix
flash-script.nix
flash-tools.nix
l4t.nix
optee.nix
samples.nix

* Remove unnecessary dependency on python2
* Set meta.platform field for packages from debs
* Rename platform in optee.nix to socType
Closes #62 
`nix flake check`

Various cleanups

---

modules/flash-script.nix

This is just a convenience script that can be run manually if we have autoUpdate enabled.
None

Add ota-apply-capsule-update-include script

---

cuda-packages.nix

- Adds supports for aarch64-linux for nsight host tools, also clean up the platforms meta information
- Make it easier to override source for nsight_systems since Nvidia still hasn't included the x86_64 version in Jetpack 5.1 deb package
- Fixed fonts issue where the applications don't render texts properly
- x86_64 builds were tested on dev laptop
- arm64 builds were tested on an Orin NX

Improved Nsight Tooling

---

samples.nix

Add a patch to fix video_decode multimedia sample package
Kudos to OE4T for already having a fix for this :)
Fixes https://github.com/anduril/jetpack-nixos/issues/131
Tested working on Orin AGX devkit

Multimedia samples video decode fix

---

kernel/0001-bpf-Generate-BTF_KIND_FLOAT-when-linking-vmlinux.patch
kernel/0002-kbuild-Quote-OBJCOPY-var-to-avoid-a-pahole-call-brea.patch
kernel/0003-kbuild-skip-per-CPU-BTF-generation-for-pahole-v1.18-.patch
kernel/0004-kbuild-Unify-options-for-BTF-generation-for-vmlinux-.patch
kernel/0005-kbuild-Add-skip_encoding_btf_enum64-option-to-pahole.patch
kernel/0006-tools-resolve_btfids-Warn-when-having-multiple-IDs-f.patch
kernel/0007-net-phy-realtek-read-actual-speed-on-rtl8211f-to-det.patch
kernel/default.nix
pkgs/uefi-firmware/default.nix

Fix inability to use 100Base-T in UEFI, and ethernet "downshifting" from 1000Base-T to 100Base-T in kernel (Xavier NX)
Tested netbooting works on Xavier NX devkit.

UEFI and Kernel Ethernet fixes

---

UPGRADE_CHECKLIST.md
device-pkgs/default.nix
modules/flash-script.nix

Fixed evaluation errors when running `nix flake check`
Ran `nix flake check`

Fix evaluation errors when running `nix flake check`

---

device-pkgs/default.nix
modules/flash-script.nix
pkgs/uefi-firmware/default.nix

Added more options to customize building of edk2
Tested patches take effects on Orin NX with AntMicro carrier board

Add more edk2 options

---

device-pkgs/default.nix
pkgs/flash-tools/default.nix

This reverts commit a829d807e1030753f81d83674e52cfa7cadc742e
Closes #153

Revert "Switch flash scripts to use from openssl to openssl_1_1"

---

README.md
modules/default.nix
pkgs/l4t/default.nix

Various fixes / improvements to graphical display on Jetson devices.
Testing status of X11/Wayland is now described in the README.md. Additionally, glxinfo and vulkaninfo work correctly.

Fix and document status of graphical output

---

.github/workflows/ci.yaml

This is helpful to see all output of derivations built, especially when potential failures occur.
N/A

Print build logs in CI

---

default.nix

Add `tests` to overlay

---

flake.nix
modules/default.nix
modules/devices.nix
modules/flash-script.nix

While adding the Orin AGX Industrial, it makes sense to go ahead and add the Xavier AGX Industrial.
This is has not been tested at all, since I do not have this hardware.

Add Xavier AGX Industrial

---

pkgs/cuda-packages/default.nix

Fixes https://github.com/anduril/jetpack-nixos/issues/237.
Tested local build succeeds.

fix nsight_system_version

---

modules/default.nix

When checking to see if we should generate the CDI support files, we should also check for the new `hardware.nvidia-container-toolkit.enable` option, since the `enableNvidia` options were deprecated.

Support new nvidia-ctk option

---

pkgs/uefi-firmware/default.nix

`patches` isn't defined in master, this breaks eval
yolo

Fix eval on nixpkgs master

---

flake.lock
flake.nix
pkgs/cuda-packages/buildFromDebs.nix
pkgs/cuda-packages/deb-builder/fixup.nix
pkgs/l4t/default.nix

Uprev to 25.05
- nix build iso_minimal, flash-xavier-nx-emmc-devkit, legacyPackages.aarch64-linux.samples.combined-test
- Boot iso_minimal

NixOS 25.05

---

pkgs/l4t/default.nix

1. l4t: debs: Refactor buildFromDeb arguments
2. l4t: gstreamer: gstreamer comes from common in JetPack 6

Package gstreamer from common repo

---

modules/default.nix

Adds a service that symlinks
`/run/opengl-driver/lib/libEGL_nvidia.so.0 -> /usr/lib/aarch64-linux-gnu/tegra-egl/libEGL_nvidia.so.0`
This allows the nvargus-daemon and libargus application to function correctly.

Create libEGL symlink for libnvscf.so library
